USE [master]
GO

CREATE DATABASE [CLS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CLS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\CLS.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CLS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\CLS_log.ldf' , SIZE = 10176KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CLS] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CLS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CLS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CLS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CLS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CLS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CLS] SET ARITHABORT OFF 
GO

ALTER DATABASE [CLS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CLS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CLS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CLS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CLS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CLS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CLS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CLS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CLS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CLS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CLS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CLS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CLS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CLS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CLS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CLS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CLS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CLS] SET RECOVERY FULL 
GO

ALTER DATABASE [CLS] SET  MULTI_USER 
GO

ALTER DATABASE [CLS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CLS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CLS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CLS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CLS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CLS] SET  READ_WRITE 
GO

USE CLS
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ChainBreakers](
	[restoreDatabaseListID] [int] NULL,
	[ID] [int] NOT NULL,
	[Directory] [varchar](1000) NULL,
	[File] [varchar](1000) NULL,
	[FileHash] [varchar](64) NULL,
	[BackupName] [nvarchar](128) NULL,
	[BackupType] [smallint] NULL,
	[FirstLSN] [numeric](25, 0) NULL,
	[LastLSN] [numeric](25, 0) NULL,
	[BackupStartDate] [datetime] NULL,
	[BackupSetGUID] [uniqueidentifier] NULL,
	[InsertDate] [datetime] NULL DEFAULT (getutcdate()),
	[Resolved] [bit] NULL DEFAULT ((0))
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO




